### ISSUE TITLE
Add a .gitignore file

### ISSUE THREAD

**Issue by tom-boyle** [tom-boyle/biocommunicator#4]
### Description  
The project is missing a `.gitignore` file to prevent unnecessary files (e.g., `node_modules`, logs, and OS-specific files) from being committed.  

### Tasks  
- [ ] Create a `.gitignore` file.  
- [ ] Add common rules (e.g., `node_modules/`, `.env`, `logs/`, `.DS_Store`).  

### Expected Outcome  
The `.gitignore` file prevents unnecessary files from being tracked by Git.  

**Labels**: `cleanup`, `code quality`

**Comment by khartist** [comment]
let me look at this

**Comment by khartist** [comment]
Could you check if contributors can push to the repo? I was trying but it says 
`remote: Permission to tom-boyle/biocommunicator.git denied to khartist.
fatal: unable to access 'https://github.com/tom-boyle/biocommunicator.git/': The requested URL returned error: 403`

Can you check the permissions? Thank you

**Comment by tom-boyle** [comment]
I've added you as a contributor. Let me know if you have any further issues.

> Could you check if contributors can push to the repo? I was trying but it says `remote: Permission to tom-boyle/biocommunicator.git denied to khartist. fatal: unable to access 'https://github.com/tom-boyle/biocommunicator.git/': The requested URL returned error: 403`
> 
> Can you check the permissions? Thank you

**Comment by khartist** [comment]
I've created a Pull Request. It seems like the issue i met earlier is because i dont have write access. But I think it should be like that.
